export default {
  UPDATE_ACTIVE_SLIDE: 'UPDATE_ACTIVE_SLIDE',
  SET_NEXT_SLIDE_INDEX: 'SET_NEXT_SLIDE_INDEX',
  SET_AUTO_SCROLL: 'SET_AUTO_SCROLL',
  SET_IS_SCROLL_N_SLIDING: 'SET_IS_SCROLL_N_SLIDING',
  TOGGLE_MOBILE_NAV: 'TOGGLE_MOBILE_NAV',
  CLOSE_MOBILE_NAV: 'CLOSE_MOBILE_NAV'
}
