export default {
  ACTIVATE_MARQUEE_SLIDER: 'ACTIVATE_MARQUEE_SLIDER',
  DEACTIVATE_MARQUEE_SLIDER: 'DEACTIVATE_MARQUEE_SLIDER',
  SWITCH_TO_LIGHT_CONTENT: 'SWITCH_TO_LIGHT_CONTENT',
  SWITCH_TO_DARK_CONTENT: 'SWITCH_TO_DARK_CONTENT',
  SWITCH_MARQUEE_TO_LIGHT_CONTENT: 'SWITCH_MARQUEE_TO_LIGHT_CONTENT',
  SWITCH_MARQUEE_TO_DARK_CONTENT: 'SWITCH_MARQUEE_TO_DARK_CONTENT',
  TOGGLE_MOBILE_NAV: 'TOGGLE_MOBILE_NAV',
  CLOSE_MOBILE_NAV: 'CLOSE_MOBILE_NAV'
}
