export default {
  UPDATE_ACTIVE_SLIDE: 'UPDATE_ACTIVE_SLIDE',
  UPDATE_PREV_SLIDE: 'UPDATE_PREV_SLIDE',
  HIDE_ACTIVE_SLIDE: 'HIDE_ACTIVE_SLIDE',
  SET_USE_PREV_AS_NEXT_SLIDE: 'SET_USE_PREV_AS_NEXT_SLIDE',
  SET_AUTO_SCROLL: 'SET_AUTO_SCROLL',
  SET_IS_SCROLL_N_SLIDING: 'SET_IS_SCROLL_N_SLIDING',
  TOGGLE_MOBILE_NAV: 'TOGGLE_MOBILE_NAV',
  CLOSE_MOBILE_NAV: 'CLOSE_MOBILE_NAV',
  SET_HEADER_SOLID: 'SET_HEADER_SOLID'
}
